services:
  sqlite-app:
    build: .
    env_file:
      - Tokens.env
    container_name: sqlite-container
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
